
CREATE TABLE LABEL (
  ACCOUNT_NAME VARCHAR(100) NOT NULL,
  REPOSITORY_NAME VARCHAR(100) NOT NULL,
  LABEL_NAME VARCHAR(64) NOT NULL,
  COLOR CHAR(7) NOT NULL,
  PRIMARY KEY (ACCOUNT_NAME, REPOSITORY_NAME, LABEL_NAME)
);
ALTER TABLE LABEL ADD CONSTRAINT IDX_LABEL_FK0 FOREIGN KEY (ACCOUNT_NAME, REPOSITORY_NAME) REFERENCES REPOSITORY (ACCOUNT_NAME, REPOSITORY_NAME);

CREATE TABLE ISSUE_LABEL (
  ACCOUNT_NAME VARCHAR(100) NOT NULL,
  REPOSITORY_NAME VARCHAR(100) NOT NULL,
  ISSUE_ID BIGINT NOT NULL,
  LABEL_NAME VARCHAR(64) NOT NULL,
  PRIMARY KEY (ACCOUNT_NAME, REPOSITORY_NAME, ISSUE_ID, LABEL_NAME)
);
ALTER TABLE ISSUE_LABEL ADD CONSTRAINT IDX_ISSUE_LABEL_FK0 FOREIGN KEY (ACCOUNT_NAME, REPOSITORY_NAME, ISSUE_ID) REFERENCES ISSUE (ACCOUNT_NAME, REPOSITORY_NAME, ISSUE_ID);
ALTER TABLE ISSUE_LABEL ADD CONSTRAINT IDX_ISSUE_LABEL_FK2 FOREIGN KEY (ACCOUNT_NAME, REPOSITORY_NAME, LABEL_NAME) REFERENCES LABEL (ACCOUNT_NAME, REPOSITORY_NAME, LABEL_NAME);
